### ISSUE TITLE
Use helm-readme-generator for documenting helm chart values

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#148]
The [Bitnami Helm Readme Generator](https://github.com/bitnami-labs/readme-generator-for-helm) is very useful to maintain up to date README files. We should generalize the use of the tool:

- [ ] All charts `values.yaml` comments need to be rewritten to follow the proper syntax
- [ ] Apply readme-generator on all charts and document how to use it in CONTRIBUTING.md
- [ ] Add a CI job that validates that the readme-generator has correctly been applied on PRs and blocks merge if it is not the case

**Comment by dblane-digicatapult** [comment]
Picking this up.
@PierreBesson do you have a `CONTRIBUTING.md` that you want to use?

**Comment by dblane-digicatapult** [comment]
Ah, that was the one that I had already made a start on 😆.

I'll get on with the others instead.

**Comment by dblane-digicatapult** [comment]
Hi,

I have a rudimentary version of `charts/common/values.yaml` and a workflow for comparing the committed readme with one that is freshly generated by CI using the `values.yaml` on a PR on my fork (Inspired heavily by Bitnamis own workflow which commits the generated README.md over the top of what is currently in existence).  @PierreBesson and team could you possibly give it a quick look over and see if this is on the right track.

Things to note:

- The workflow job `readme-comparison` currently fails as I have not yet updated the other `values.yaml` files, 
- The `## @section` parts meant I had to reorganise the location of some values.  Let me know if you prefer a different layout of sections or their contents.
- The descriptions have again been heavily borrowed from Bitnami, if you are unhappy with them then please comment on them when I do a PR across to this repo rather than the PR on my fork.

https://github.com/dblane-digicatapult/helm-charts/pull/1

**Comment by PierreBesson** [comment]
I have created a [generated-readme-values branch](https://github.com/paritytech/helm-charts/tree/generated-readme-values) to which your should submit all readme revamp PRs.

**Comment by PierreBesson** [comment]
Replaced by #248
